### ISSUE TITLE
Warning  You cannot authorize that page

### ISSUE THREAD

**Issue by dukenst2006** [julles/capsule#1]
Hi,
Great work @julles  ! congratulate you for this initiative, hope you continue with this awesome project. Keep it on !
I have an issue even i connected as super admin it's give this message "Warning  You cannot authorize that page" when i try to go to role. aany idea !!
Thanks !!

**Comment by julles** [comment]
hi @dukenst2006 
if you follow the instructions readme.md?
I just now tried to install  and goes well

![gitcapsule](https://cloud.githubusercontent.com/assets/8998059/14009021/3b1ff4d6-f1ba-11e5-809b-a5a459942760.png)
